name = "sec-risks-frontend"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_flags = ["nodejs_compat"]

[vars]
PUBLIC_APP_URL = "https://vanerisks.com"
PUBLIC_SUPABASE_URL = "https://vcbwbrzorjrfxsypabhl.supabase.co"