name = "sec-risks-frontend"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_flags = ["nodejs_compat"]

[vars]
PUBLIC_APP_URL = "https://vanerisk.com"
PUBLIC_SUPABASE_URL = "https://vcbwbrzorjrfxsypabhl.supabase.co"

[[kv_namespaces]]
binding = "RATE_LIMITS"
id = "c8c13aa514e14eef946de1ae98ee59e6"